rand_state: 42

test_size: 0.25

cv_folds: 5

mice_iters: 3

max_iters: 1000

n_trials: 100

n_jobs: 5

share_non_null: 0.5

min_samples_leaf: 20

smoothing: 10

write_encoding_dict: True
log_label: True

dir_list: ['/oak/stanford/groups/deho/proptax/models/cook_rf_14_features_log_label_mae_loss_drop_outliers_cook_data/hyperparams/studies',
        '/oak/stanford/groups/deho/proptax/models/cook_rf_14_features_log_label_mae_loss_drop_outliers_cook_data/hyperparams/samplers',
        '/oak/stanford/groups/deho/proptax/models/cook_rf_14_features_log_label_mae_loss_drop_outliers_cook_data/hyperparams/best_params',
        '/oak/stanford/groups/deho/proptax/models/cook_rf_14_features_log_label_mae_loss_drop_outliers_cook_data/hyperparams/trials',
        '/oak/stanford/groups/deho/proptax/models/cook_rf_14_features_log_label_mae_loss_drop_outliers_cook_data/data',
        '/oak/stanford/groups/deho/proptax/models/cook_rf_14_features_log_label_mae_loss_drop_outliers_cook_data/logs',
        '/oak/stanford/groups/deho/proptax/models/cook_rf_14_features_log_label_mae_loss_drop_outliers_cook_data/encoders',
        '/oak/stanford/groups/deho/proptax/models/cook_rf_14_features_log_label_mae_loss_drop_outliers_cook_data/config',
        '/oak/stanford/groups/deho/proptax/models/cook_rf_14_features_log_label_mae_loss_drop_outliers_cook_data/model'
]

raw_path: '/oak/stanford/groups/deho/proptax/raw/cook_sales_assessments_county_prices_2023.csv'

study_dir: '/oak/stanford/groups/deho/proptax/models/cook_rf_14_features_log_label_mae_loss_drop_outliers_cook_data/hyperparams/studies/studies'

sampler_path: '/oak/stanford/groups/deho/proptax/models/cook_rf_14_features_log_label_mae_loss_drop_outliers_cook_data/hyperparams/samplers/sampler.pkl'

params_path: '/oak/stanford/groups/deho/proptax/models/cook_rf_14_features_log_label_mae_loss_drop_outliers_cook_data/hyperparams/best_params/best-params.pkl'

trials_path: '/oak/stanford/groups/deho/proptax/models/cook_rf_14_features_log_label_mae_loss_drop_outliers_cook_data/hyperparams/trials/trials.pkl'

model_dir: '/oak/stanford/groups/deho/proptax/models/cook_rf_14_features_log_label_mae_loss_drop_outliers_cook_data/model'

proc_data_dir: '/oak/stanford/groups/deho/proptax/models/cook_rf_14_features_log_label_mae_loss_drop_outliers_cook_data/data'

log_dir: '/oak/stanford/groups/deho/proptax/models/cook_rf_14_features_log_label_mae_loss_drop_outliers_cook_data/logs'

encoding_path: '/oak/stanford/groups/deho/proptax/models/cook_rf_14_features_log_label_mae_loss_drop_outliers_cook_data/encoders'

fips: '17031'

county_name: 'cook'
  
model_id: 'cook_rf_14_features_log_label_mae_loss_drop_outliers_cook_data'

model_type: 'rf'

meta: ['meta_sfh', 'ASSESSED_YEAR', 'SALE_YEAR', 'CLIP', 'fips', 'MARKET_TOTAL_VALUE']

id: ['CLIP']

geo: ['fips']
 
time: ['ASSESSED_YEAR',
       'SALE_YEAR']

ignore: [ 'WARRANTY_GRANT_IND',
        'FORE_QC_PROB_IND']

benchmark: ['MARKET_TOTAL_VALUE']

label: 'SALE_AMOUNT'

binary: []

continuous: ['char_yrblt',
 'char_beds',
 'char_bldg_sf',
 'char_stories',
 'char_fbath',
 'char_gar1_size',
 'char_land_sf']

categorical: ['char_air_cat',
 'char_bsmt_cat',
 'char_bsmt_fin_cat',
 'char_ext_wall_cat',
 'char_gar1_cat',
 'char_roof_material_cat',
 'char_style_cat']
loss_func: mae_loss
drop_lowest_ratios: True
