model_descriptors:

    fips: '17031'

    model_type: 'rf'

    model_label: 'ablation_study'

model_params:

  n_features: 10

  log_label: True

  rand_state: 42

  test_size: 0.25

  cv_folds: 5

  mice_iters: 3

  max_iters: 1000

  n_trials: 100

  n_jobs: 5

  share_non_null: 0.5

  min_samples_leaf: 20

  smoothing: 10

  write_encoding_dict: True

  loss_func: mae_loss

features: 

  continuous: None

  categorical: None

  meta: ['meta_sfh', 'ASSESSED_YEAR', 'SALE_YEAR', 'CLIP', 'fips', 'tract', 'block_group', 'MARKET_TOTAL_VALUE']

  label: 'SALE_AMOUNT'

  time: ['ASSESSED_YEAR', 'SALE_YEAR']

  sale_date_col : 'sale_date'

  binary : []

paths:

    raw_path: '/oak/stanford/groups/deho/proptax/raw/corelogic_census_2023.csv'

    study_dir: '/oak/stanford/groups/deho/proptax/models/cook_rf_3_features_log_label/hyperparams/studies/studies'

    sampler_path: '/oak/stanford/groups/deho/proptax/models/cook_rf_3_features_log_label/hyperparams/samplers/sampler.pkl'

    params_path: '/oak/stanford/groups/deho/proptax/models/cook_rf_3_features_log_label/hyperparams/best_params/best-params.pkl'

    trials_path: '/oak/stanford/groups/deho/proptax/models/cook_rf_3_features_log_label/hyperparams/trials/trials.pkl'

    model_dir: '/oak/stanford/groups/deho/proptax/models/cook_rf_3_features_log_label/model'

    proc_data_dir: '/oak/stanford/groups/deho/proptax/models/cook_rf_3_features_log_label/data'

    log_dir: '/oak/stanford/groups/deho/proptax/models/cook_rf_3_features_log_label/logs'

    encoding_path: '/oak/stanford/groups/deho/proptax/models/cook_rf_3_features_log_label/encoders'
