continuous: ['char_yrblt', 
    'char_beds', 
    'char_bldg_sf', 
    'char_ground_sf', 
    'char_second_sf', 
    'char_base_fin_sf', 
    'char_base_unfin_sf', 
    'char_stories', 
    'char_nbath', 
    'char_fbath', 
    'char_hbath', 
    'char_n_frpl', 
    'char_gar1_size', 
    'char_gar1_sf', 
    'char_bq_ordinal', 
    'char_land_sf', 
    'char_frontage_sf', 
    'char_depth_sf']

categorical: ['char_air_cat',
   'char_bsmt_cat',
   'char_bsmt_fin_cat',
   'char_ext_wall_cat',
   'char_gar1_cat',
   'char_floor_cat',
   'char_bq_cat',
   'char_heat_cat',
   'char_roof_material_cat',
   'char_style_cat',
   'char_found_cat',
   'char_fuel_typ_cat',
   'char_sewer_cat',
   'char_water_cat',
   'char_elec_cat']

census_tract: ['census_pct_children_tract',
    'census_pct_senior_tract',
    'census_med_age_tract',
    'census_pct_married_hh_tract',
    'census_pct_single_hh_tract',
    'census_pct_high_school_tract',
    'census_pct_college_tract',
    'census_pct_graduate_tract',
    'census_pct_poverty_tract',
    'census_med_hh_inc_tract',
    'census_med_per_cap_inc_tract',
    'census_pct_snap_tract',
    'census_unemp_rate_tract',
    'census_med_yr_built_tract',
    'census_pct_renter_occ_tract']

census_block_group: ['census_pct_children_bg',
    'census_pct_senior_bg',
    'census_med_age_bg',
    'census_pct_married_hh_bg',
    'census_pct_single_hh_bg',
    'census_pct_high_school_bg',
    'census_pct_college_bg',
    'census_pct_graduate_bg',
    'census_pct_poverty_bg',
    'census_med_hh_inc_bg',
    'census_med_per_cap_inc_bg',
    'census_pct_snap_bg',
    'census_unemp_rate_bg',
    'census_med_yr_built_bg',
    'census_pct_renter_occ_bg']

label: 'SALE_AMOUNT'
