paths:
  
  data_path: 'oak/stanford/groups/deho/proptax/clean/corelogic_census_2018_2023.csv'
  
  feature_order_path: '../../config/feature_order_2023.csv'
  
  fips_path: 'oak/stanford/groups/deho/proptax/clean/shuffled_fips.csv'
  
  results_path: 'oak/stanford/groups/deho/proptax/models/lasso_loop/results/lasso_results.csv'

  log_path: 'oak/stanford/groups/deho/proptax/models/lasso_loop/logs'

  sampler_path: 'oak/stanford/groups/deho/proptax/models/lasso_loop/hyperparams/sampler.pkl'

  params_path: 'oak/stanford/groups/deho/proptax/models/lasso_loop/hyperparams/best_params.pkl'

  trials_path: 'oak/stanford/groups/deho/proptax/models/lasso_loop/hyperparams/trials.csv'

model_params:

  share_non_null: 0.5

  random_state: 42

  wins_pctile: 1

  log_label: True

  n_trials: 25

  loss_func: mae_loss

features:

  continuous: ['char_yrblt', 
    'char_beds', 
    'char_bldg_sf', 
    'char_ground_sf', 
    'char_second_sf', 
    'char_base_fin_sf', 
    'char_base_unfin_sf', 
    'char_stories', 
    'char_nbath', 
    'char_fbath', 
    'char_hbath', 
    'char_n_frpl', 
    'char_gar1_size', 
    'char_gar1_sf', 
    'char_bq_ordinal', 
    'char_land_sf', 
    'char_frontage_sf', 
    'char_depth_sf']

  categorical: ['char_air_cat',
   'char_bsmt_cat',
   'char_bsmt_fin_cat',
   'char_ext_wall_cat',
   'char_gar1_cat',
   'char_floor_cat',
   'char_bq_cat',
   'char_heat_cat',
   'char_roof_material_cat',
   'char_style_cat',
   'char_found_cat',
   'char_fuel_typ_cat',
   'char_sewer_cat',
   'char_water_cat',
   'char_elec_cat']

  meta: ['meta_sfh', 'ASSESSED_YEAR', 'SALE_YEAR', 'CLIP', 'fips', 'tract', 'block_group', 'MARKET_TOTAL_VALUE', 'ASSESSED_TOTAL_VALUE', 'APPRAISED_TOTAL_VALUE', 'CALCULATED_TOTAL_VALUE', 'CALCULATED_TOTAL_VALUE_SOURCE_CODE', 'TOTAL_TAX_AMOUNT', 'NET_TAX_AMOUNT', 'latitude', 'longitude']

  label: 'SALE_AMOUNT'

  time: ['ASSESSED_YEAR', 'SALE_YEAR']

  sale_date_col : 'sale_date'

  binary : []