rand_state: 42

test_size: 0.25

cv_folds: 5

mice_iters: 3

max_iters: 1000

n_trials: 20

n_jobs: 5

share_non_null: 0.5

min_samples_leaf: 20

smoothing: 10

write_encoding_dict: True

raw_path: '/oak/stanford/groups/deho/proptax/raw/sales_assessments_2023.csv'

study_dir: '/oak/stanford/groups/deho/proptax/models/rf_house_char_target_encode/hyperparams/studies'

sampler_path: '/oak/stanford/groups/deho/proptax/models/rf_house_char_target_encode/hyperparams/samplers/sampler.pkl'

params_path: '/oak/stanford/groups/deho/proptax/models/rf_house_char_target_encode/hyperparams/best_params/best-params.pkl'

trials_path: '/oak/stanford/groups/deho/proptax/models/rf_house_char_target_encode/hyperparams/trials/trials.pkl'

proc_data_dir: '/oak/stanford/groups/deho/proptax/models/rf_house_char_target_encode/data'

log_dir: '/oak/stanford/groups/deho/proptax/models/rf_house_char_target_encode/logs'

encoding_path: '/oak/stanford/groups/deho/proptax/models/rf_house_char_target_encode/encoders'

#fips: 17031 # cook county

fips: 48201

meta: ['meta_sfh', 'ASSESSED_YEAR', 'SALE_YEAR', 'CLIP', 'tract_id', 'fips', 'MARKET_TOTAL_VALUE']

id: ['CLIP']

geo: ['tract_id',
    'fips']
 
time: ['ASSESSED_YEAR',
       'SALE_YEAR']

ignore: [ 'WARRANTY_GRANT_IND',
        'FORE_QC_PROB_IND']

benchmark: ['MARKET_TOTAL_VALUE']

label: 'SALE_AMOUNT'

binary: []

continuous: ['char_yrblt', 
    'char_beds', 
    'char_bldg_sf', 
    'char_ground_sf', 
    'char_second_sf', 
    'char_base_fin_sf', 
    'char_base_unfin_sf', 
    'char_stories', 
    'char_nbath', 
    'char_fbath', 
    'char_hbath', 
    'char_n_frpl', 
    'char_gar1_size', 
    'char_gar1_sf', 
    'char_bq_ordinal', 
    'char_land_sf', 
    'char_frontage_sf', 
    'char_depth_sf']

categorical: ['char_air_cat',
   'char_bsmt_cat',
   'char_bsmt_fin_cat',
   'char_ext_wall_cat',
   'char_gar1_cat',
   'char_floor_cat',
   'char_bq_cat',
   'char_heat_cat',
   'char_roof_material_cat',
   'char_style_cat',
   'char_found_cat',
   'char_fuel_typ_cat',
   'char_sewer_cat',
   'char_water_cat',
   'char_elec_cat']
